version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rootuser
      - RABBITMQ_DEFAULT_PASS=rootpass
    ports:
      - 5672:5672
      - 15672:15672
